-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 15b678e9c67c42765c3d579e40672a332f4366d7
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: flake8
        exclude: "\
            (.*migrations.*)|\
            (configs/vagrant/settings_local.py)|\
            (docs/.*)|\
            (kitsune/settings.*)|\
            (kitsune/sumo/db_strings.py)|\
            (scripts/contributor_counts.py)|\
            (scripts/crontab/gen-crons.py)|\
            (scripts/peep.py)|\
            (scripts/sprint_report.py)|\
            (scripts/year_in_review.py)"
        args: [--max-line-length=99]
