sudo: required
language: python
python: 2.7
services:
  - docker
install:
  - pip install -U docker-compose
  - cp .env-travis .env
  - docker-compose up -d mariadb
  - docker-compose up -d elasticsearch
  - docker-compose up -d redis
  - docker-compose build
  - docker-compose run --user root web ./manage.py nunjucks_precompile
  - docker-compose run --user root web ./manage.py compilejsi18n
  - docker-compose run --user root web ./manage.py collectstatic --noinput
script:
  - docker-compose run --user root web flake8 kitsune
  - docker-compose run --user root web ./node_modules/.bin/mocha --compilers js:babel/register --recursive kitsune/*/static/*/js/tests/* $@
  - docker-compose run --user root -e REUSE_STATIC=1 web ./manage.py test --noinput --nologcapture -a '!search_tests' --with-nicedots
notifications:
  email: false
  irc:
    channels:
    - irc.mozilla.org#sumodev
    on_success: always
    on_failure: always
