sudo: required
language: python
python:
- '2.7'
services:
- docker
cache:
- pip
- npm
- yarn
before_install:
- echo "Can I echo things in before_install?"
- echo Test secret is $DOCKER_USERNAME
- echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
- export GIT_SHA=${TRAVIS_COMMIT}
- make pull
script:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    echo would execute sh "scripts/lint-l10n-repo.sh --push";
  fi
- echo Test secret is hopefully still $DOCKER_USERNAME
- make build-ci
- make lint-ci
- make test-js-ci
- make test-ci
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    make push-image;
  fi
# Add secrets with `travis encrypt --add` with the form of MY_ENV_VAR=MySuperSecret
env:
  global:
  - secure: TCeF41hX0NAt0fUKYdUb4R65zllxkpuYq5iwKT1AXeCLn6l9qf14g8LmK6Nvxd7hAwXzvRxmKdQQa15XYFvhuEU4rPSbLgEO3lX8BFqpxA7l6+waXhyy8qb92QvyeiY6PvEcFyk1oqwPaANhtU4I9/oNhbYKBYqKRU4MoBVN/hU=
notifications:
  slack:
    secure: Mq/2mpiKRd5ap2Re7PyGM4K7vWvN2bo1kSHd9XyeZ+LiLrLkm14QUYAbUe3WcQUDUeRtSR8zVHKRGxmBXc+TNB/Q/MCm3vgxspdqO6ScLqX3FAqwc6MVq494gn22o7fp5z/EwzdsWUlTOFUENpRzQmsF0sf3LAuijsLWvPxk4pM=
