sudo: required
language: python
python:
- '2.7'
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_f6343abeba05_key -iv $encrypted_f6343abeba05_iv -in ci\/test-l10nfork-key.enc -out ci\/test-l10nfork-key -d
- export GIT_SHA=${TRAVIS_COMMIT}
- make pull
script:
- sh scripts/lint-l10n-repo.sh --push;
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then 
    ./scripts/lint-l10n-repo.sh --push;
  fi
- make build-ci
- make lint-ci
- make test-js-ci
- make test-ci
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then 
    ./docker/bin/push-docker-images.sh;
  fi
- if [[ "$TRAVIS_BRANCH" == "travis" ]]; then 
    ./docker/bin/push-docker-images.sh;
  fi
env:
  global:
  - secure: j3j4ARHbQwvNMx2W/JHGkLHMyDMnaLT8D8E9brSu2k1+0BZiEfZU1wmPhmPZ/GuorjZJvwB7K7n29wi89rR+VQmZlro/Eq+Cyi/2k6kVItsSFiDiMad0CxwD9nkrYMQcKwA1FzinlizoJkmAsz27Y7AkPFLyR+VofFEkJ/hWKhg=
  - secure: Pc3xhQvrSG0XeBxZm4U3EChlHlhwPoMKQMlAuJuhjNV3EFtbhFqbp7K0m4zXmauX4qe4pWUGiC2Y5zg2NgemXkIaxQqrs7uPDYZF1FHq2bshN4//fBgLZ72nh9zpb0fdCR5Ij1EOTtTOt2iEFYPFeCxoV/NBlHEvv0Rg3BioIbA=
  - DOCKER_REPO=itsre/sumo-kitsune-travis
notifications:
  slack:
    secure: Mq/2mpiKRd5ap2Re7PyGM4K7vWvN2bo1kSHd9XyeZ+LiLrLkm14QUYAbUe3WcQUDUeRtSR8zVHKRGxmBXc+TNB/Q/MCm3vgxspdqO6ScLqX3FAqwc6MVq494gn22o7fp5z/EwzdsWUlTOFUENpRzQmsF0sf3LAuijsLWvPxk4pM=
