sudo: required
language: python
python: 2.7
env:
  global:
    - DEBUG=False
services:
  - docker
install:
  - pip install -U docker-compose
  - docker-compose build
script:
  - docker-compose run web flake8 kitsune
  - docker-compose run web ./manage.py test
notifications:
  email: false
  irc:
    channels:
    - irc.mozilla.org#sumodev
    on_success: always
    on_failure: always
