sudo: required
language: python
python:
- '2.7'
services:
- docker
before_install:
- echo "Can I echo things in before_install?"
- echo Test secret is $DOCKER_USERNAME
- echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
- export GIT_SHA=${TRAVIS_COMMIT}
- make pull
script:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    echo would execute sh "scripts/lint-l10n-repo.sh --push";
  fi
- echo Test secret is hopefully still $DOCKER_USERNAME
- make build-ci
- make lint-ci
- make test-js-ci
- make test-ci
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    make push-image;
  fi
# Add secrets with `travis encrypt` with the form of `export MY_ENV_VAR=MySuperSecret`
env:
  global:
  # Dockerhub
  - secure: "j3j4ARHbQwvNMx2W/JHGkLHMyDMnaLT8D8E9brSu2k1+0BZiEfZU1wmPhmPZ/GuorjZJvwB7K7n29wi89rR+VQmZlro/Eq+Cyi/2k6kVItsSFiDiMad0CxwD9nkrYMQcKwA1FzinlizoJkmAsz27Y7AkPFLyR+VofFEkJ/hWKhg="
  # Dockerhub
  - secure: "Pc3xhQvrSG0XeBxZm4U3EChlHlhwPoMKQMlAuJuhjNV3EFtbhFqbp7K0m4zXmauX4qe4pWUGiC2Y5zg2NgemXkIaxQqrs7uPDYZF1FHq2bshN4//fBgLZ72nh9zpb0fdCR5Ij1EOTtTOt2iEFYPFeCxoV/NBlHEvv0Rg3BioIbA="
notifications:
  slack:
    secure: Mq/2mpiKRd5ap2Re7PyGM4K7vWvN2bo1kSHd9XyeZ+LiLrLkm14QUYAbUe3WcQUDUeRtSR8zVHKRGxmBXc+TNB/Q/MCm3vgxspdqO6ScLqX3FAqwc6MVq494gn22o7fp5z/EwzdsWUlTOFUENpRzQmsF0sf3LAuijsLWvPxk4pM=
