version: '2.1'
services:
  web:
    build: .
    command: ./manage.py runserver 0.0.0.0:8000
    user: kitsune
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bower_components:/app/bower_components
    depends_on:
      - mariadb
      - elasticsearch
      - redis
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=*
      - BROKER_URL=redis://redis:643
      - REDIS_DEFAULT_URL=redis://redis:6379/1
      - REDIS_HELPFULVOTES_URL=redis://redis:6379/2
      - CACHE_URL=redis://redis:6379/3
      - CELERY_ALWAYS_EAGER=True
      - CSRF_COOKIE_SECURE=False
      - DATABASE_URL=mysql://root:kitsune@mariadb:3306/kitsune
      - DOMAIN=localhost
      - ES_URLS=elasticsearch:9200
      - SESSION_COOKIE_SECURE=False
      - SITE_URL=http://localhost:8000
      - SECRET_KEY=foo
  mariadb:
    image: mariadb:10.0
    environment:
      - MYSQL_ROOT_PASSWORD=kitsune
      - MYSQL_USER=kitsune
      - MYSQL_PASSWORD=kitsune
      - MYSQL_DATABASE=kitsune
    entrypoint:
      - docker-entrypoint.sh
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    volumes:
      - mysqlvolume:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:2.4

  redis:
    image: redis:3

volumes:
    mysqlvolume:
    node_modules:
    bower_components:
