apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sumo-dev-web
  namespace: sumo-dev
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: sumo-dev-web
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
